# Generated by Django 5.2.5 on 2025-08-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('graduacao', models.CharField(choices=[('soldado', 'Soldado'), ('cabo', 'Cabo'), ('sargento', 'Sargento'), ('subtenente', 'Subtenente'), ('tenente', 'Tenente'), ('capitao', 'Capitão'), ('major', 'Major'), ('tenente_coronel', 'Tenente-Coronel'), ('coronel', 'Coronel')], max_length=20)),
            ],
        ),
    ]
