# Generated by Django 5.2.5 on 2025-08-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='usuarios.usuario'),
        ),
    ]
